### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by rjrudman** [SOBotics/Higgs#10]
How should the sitemap be arranged?

Suggesting the following:

`higgs.sobotics.org/hydrant/reports` shows all reports for hydrant
`higgs.sobotics.org/reports` shows all reports across the system

`higgs.sobotics.org/report/1` displays report '1'. Should it redirect to `higgs.sobotics.org/hydrant/1` if it was reported by hydrant? 

What happens if we visit `higgs.sobotics.org/hydrant/1`, but hydrant is the incorrect dashboard?

**Comment by Bhargav-Rao** [comment]
I think you can take some inspiration from the suggested edits queue. The suggested edits have an report ID, and the other reviews (along with suggested edit queue) have a report ID, but the suggested edit report ID would auto redirect to the review queue report ID. 

Example [`https://stackoverflow.com/suggested-edits/3590340`](https://stackoverflow.com/suggested-edits/3590340) goes to [`https://stackoverflow.com/review/suggested-edits/18983598`](https://stackoverflow.com/review/suggested-edits/18983598).

**Comment by rjrudman** [comment]
@Bhargav-Rao Agreed. `/report...` will now redirect to `/{dashboardName}/report/...`. If the wrong dashboard is in the URL, it'll also be redirected
