### ISSUE TITLE
Allow bots to provide feedback on behalf of a user

### ISSUE THREAD

**Issue by rjrudman** [SOBotics/Higgs#19]
Users can provide feedback in chat to a bot. Bots therefore should be able to provide feedback on behalf of that user.

**Comment by pbdevch** [comment]
Do we have Bots that do that right now? I can't think of one except Smokey with Autoflagging

**Comment by Bhargav-Rao** [comment]
Eh, aren't you providing feedback to literally every other bot in the room? What Rob's telling is:  

@pbdevch  --> `@Queen tp` --> Queen stores *chade has fed tp* --> Queen calls Hydrant and informs that chade has fed tp --> Hydrant stores it.

**Comment by pbdevch** [comment]
@Bhargav-Rao Ahh, now it get it. I thought of it the way SmokeDetector/MS is doing automatic flagging right now.
