### ISSUE TITLE
Add disclaimer that data comes from SE

### ISSUE THREAD

**Issue by rjrudman** [SOBotics/Higgs#3]

**Comment by pbdevch** [comment]
Proposal for the disclaimer (combination from [MetaSmoke](https://metasmoke.erwaysoftware.com/) and the [SOBotics website](https://sobotics.org/) disclaimers):

> We are [SOBotics](https://sobotics.org/) (not [Stack Exchange](https://stackexchange.com/)). We make [nice bots](https://github.com/SOBotics). We use data from the [Stack Exchange API](http://api.stackexchange.com/) in our work.

**Comment by Bhargav-Rao** [comment]
Similar to the one on CP:

> Made by [SOBotics](https://sobotics.org/). Published on [StackApps]. Source code on [GitHub](https://github.com/SOBotics/Higgs). Content provided by [Stack Exchange API](https://api.stackexchange.com/) through the cc by-sa 3.0 license
