### ISSUE TITLE
Review: Move "Skip" button to the feedback-buttons

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Higgs#49]
In the SE review-queues, the "skip"-button is always next to the other buttons. This would make skipping much easier

![screenshot](https://user-images.githubusercontent.com/2721240/40256517-0882fba8-5aeb-11e8-8239-ee7aa5e95a69.png)

**Comment by rjrudman** [comment]
This might take a little bit longer than expected, as the content under the first `<hr />` is an encapsulated component.

I'll definitely have a look into this, as I agree it'd be nice to have the buttons grouped together.

**Comment by rjrudman** [comment]
I took the easy route and simply removed the skip button. Reports can expose their own skip button (in the picture here, it's `sk`). Otherwise, things get pretty complicated.
