### ISSUE TITLE
Logo isn't loading on Safari

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Higgs#54]
<img width="281" alt="bildschirmfoto 2018-05-25 um 20 55 09" src="https://user-images.githubusercontent.com/2721240/40561583-09499f2e-605e-11e8-92bc-6c6f58f87cbd.png">

The logo fails to load in Safari 11.1 (13605.1.33.1.4) on macOS 10.13.4.

Apparently, Safari can't display `.webp`-files. (actually, I've never seen that file-extension before)

**Comment by rjrudman** [comment]
Fixed now, thanks
