### ISSUE TITLE
Higgs becomes unusable after logging in

### ISSUE THREAD

**Issue by GolfingSuccess** [SOBotics/Higgs#58]
In Chrome 69, Windows 10, whenever I try to log into Higgs, the whole page turns white, and this error is output on the console:

```
ERROR DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at t.getAuthDetails (https://higgs.sobotics.org/main.b232014594aa1a1fb01e.bundle.js:1:374305)
    at new t (https://higgs.sobotics.org/main.b232014594aa1a1fb01e.bundle.js:1:374043)
    at https://higgs.sobotics.org/main.b232014594aa1a1fb01e.bundle.js:1:270690
    at Qn (https://higgs.sobotics.org/main.b232014594aa1a1fb01e.bundle.js:1:270880)
    at Kn (https://higgs.sobotics.org/main.b232014594aa1a1fb01e.bundle.js:1:270466)
    at t.get (https://higgs.sobotics.org/main.b232014594aa1a1fb01e.bundle.js:1:281185)
    at zi (https://higgs.sobotics.org/main.b232014594aa1a1fb01e.bundle.js:1:285060)
    at Vi (https://higgs.sobotics.org/main.b232014594aa1a1fb01e.bundle.js:1:284186)
    at Li (https://higgs.sobotics.org/main.b232014594aa1a1fb01e.bundle.js:1:283060)
    at hr (https://higgs.sobotics.org/main.b232014594aa1a1fb01e.bundle.js:1:293599)
Q @ main.b232014594aa1a1fb01e.bundle.js:1
```

When I delete my LocalStorage, it goes back to normal (although logged out).

This also happens on Firefox 62.0, and I can't use Higgs at all from my laptop. I've determined that none of my extensions or userscripts are at fault.

**Comment by rjrudman** [comment]
Back now! Could you please log into Higgs and run the following:

```localStorage.getItem('access_token')```

This token is secret, but you should see an alphanumeric string in the form of 'abc123.def456.ghi789'. Could you paste the middle portion here (def456)? This section of the token is not secret, and is safe to share here.

If the token you see isn't in this format (three blocks of base64 text separated by periods), let me know.

**Comment by GolfingSuccess** [comment]
@rjrudman Um, did you change anything? I think the problem has disappeared, but let's wait a bit. [yadayadayada.]`eyJ1bmlxdWVfbmFtZSI6IkVLb25zIiwiYWNjb3VudElkIjoiMjQ3NDk1NSIsInJldmlld2VyIjoiIiwibmJmIjoxNTM2OTM3NDUyLCJleHAiOjE1Mzc1NDIyNTIsImlhdCI6MTUzNjkzNzQ1Mn0`[.yadayadayada]

**Comment by rjrudman** [comment]
Nope, I didn't change anything. That token also stores your username, I don't suppose it had something to do with the greek characters you previously had..?

I did see an error a few days ago relating to authentication, it may have coincided with your login attempt.

**Comment by GolfingSuccess** [comment]
I hope Greek chars are supported... and yeah, I had those Greek chars since...2013, time to change that. :-)

**Comment by rjrudman** [comment]
They *should* be supported, but never tested :). I saw a null reference exception, which isn't very helpful. I'm guessing it may be related, but I'm not certain. Since this is working for you now, I'm going to close the issue as there's not much I can do to investigate.. but if you run into it again, feel free to ping me and I'll re-open it.
