### ISSUE TITLE
Move the version/revision to the header

### ISSUE THREAD

**Issue by Filnor** [SOBotics/Higgs#60]
Since the design of Higgs is pretty similar to Sentinel and Redunda, the version should also be in the header. Example from Redunda:
![version_redunda](https://user-images.githubusercontent.com/7314572/48695408-5d477a80-ebdf-11e8-9684-1a657eba83c8.png)

**Comment by rjrudman** [comment]
The site's influenced by metasmoke more out of laziness (and lack of design skills), rather than a deliberate attempt. 

The footer was a bit tricky to get working, and I personally prefer it at the bottom, so marking this as won't-do. Thanks for the suggestion anyway :)
