### ISSUE TITLE
Rodgort

### ISSUE THREAD

**Issue by Filnor** [SOBotics/Higgs#62]
When I try to access a Hydrant report, I get redirect to http://higgs.sobotics.org/ and a blank page with the title "Rodgort" is shown.
![image](https://user-images.githubusercontent.com/7314572/49936550-7d174900-fed4-11e8-9883-886f08bb6fbb.png)

Got the access to Hydrant borked?

**Comment by FelixSFD** [comment]
Works for me with HTTPS in Firefox 63.0.3 on Windows 10

**Comment by rjrudman** [comment]
Fixed now! I added a new site without a domain name binding, which broke everything. Thanks for the report
