### ISSUE TITLE
Add 404 pages

### ISSUE THREAD

**Issue by rjrudman** [SOBotics/Higgs#9]

**Comment by rjrudman** [comment]
Added a barebones page. Looking for someone who can come up with a flashier design.

http://45.77.238.226:5555/Hydrant/report/11115

**Comment by Bhargav-Rao** [comment]
Post a message in the room and pin it. Let's see if others can come up with
something nice.

**Comment by Bhargav-Rao** [comment]
This XKCD seems like a good one https://www.xkcd.com/1437/. Something
related to "lost" and "Higgs".

**Comment by rjrudman** [comment]
I like it. I've pushed an update to include the comment. Here's what it looks like:

![image](https://user-images.githubusercontent.com/709585/36943155-d953d486-1fd7-11e8-92dc-810efe1df287.png)

**Comment by K-Davis1** [comment]
Probably would be a good idea to redirect the user to the home page when clicking the image itself, rather than to xkcd (which you already credited below with a hyperlink).

**Comment by rjrudman** [comment]
@K-Davis1 The minimum xkcd asks for is a link to the license page (which the 'xkcd' text links to). I think it's nice to also link to the actual comic as well.

I'm not sure the 404 image should link to the home page.. that's not a very common design, and the 'Higgs' logo will (should?) do that. 

That said, though, if others disagree, I'm happy to change how it links

**Comment by pbdevch** [comment]
I'd add a link or a button for going back to the homepage, additionally to the logo. But I strongly disagree linking the image, it (as alrady stated by @rjudman) is very uncommon to use an image for this purpose.
